name: Update version

on: 
  pull_request:
    branches: [main]
  push:
    branches: [main]
    paths: 
      - '.github/workflows/update.yml'
      - './o.py'
      - './a.py'
      - './optifine.py'
  schedule:
    - cron: '0 * * * *'

jobs:
  update_version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: set time
        shell: bash
        run: |
          sudo timedatectl set-timezone 'Asia/Shanghai'
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
      - name: Check update
        id: check_update
        run: |
          python3 optifine.py
          wget https://bmclapi2.bangbang93.com/optifine/versionList -O versionlist.json
          git add -A
          if git diff-index --quiet HEAD; then
            # No changes
            echo 'changed=false' >> $GITHUB_OUTPUT
          else
            # Changes detected
            echo 'changed=true' >> $GITHUB_OUTPUT
          fi
      - name: Fetch version
        if: steps.check_update.outputs.changed == 'true'
        run: |
          # echo "run o!"
          # python3 o.py
          # echo "Done!"
          # echo "run a!!"
          # python3 a.py
          # echo "Done!!"
          echo "run g!!!"
          python3 g.py
          echo "Done!!!"
      - name: Commit
        if: steps.check_update.outputs.changed == 'true'
        shell: bash
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "**Optifine 更新版本啦，请注意与 Forge 的兼容情况**

          （`date '+%Y-%m-%d %H:%M:%S'`）
          GitHub Action: https://github.com/${{ github.repository }}/actions/runs/$GITHUB_RUN_ID
            "
      - name: Push changes
        if: steps.check_update.outputs.changed == 'true'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
